services:
  frontend:
    image: antoniopapa1991/admin-frontend
    depends_on:
      - backend
    networks:
      - app
    ports:
      - 3000:3000 # Map frontend port to the host (adjust if needed)
    restart: unless-stopped

  backend:
    container_name: admin_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app
    restart: unless-stopped

  db:
    container_name: admin_db
    image: mysql:8
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - app
    restart: unless-stopped

networks:
  app:
